insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Duck - Legs', 368.72);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Asparagus - Mexican', 459.37);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'External Supplier', 746.37);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Oil - Food, Lacquer Spray', 280.45);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Lemonade - Kiwi, 591 Ml', 526.25);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Piping Jelly - All Colours', 704.44);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Melon - Honey Dew', 726.17);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Buffalo - Short Rib Fresh', 174.29);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Cumin - Whole', 299.35);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Yogurt - Assorted Pack', 620.22);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Vinegar - Tarragon', 550.63);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Icecream - Dstk Strw Chseck', 2.29);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Lamb - Ground', 598.94);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Soy Protein', 834.91);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Veal - Bones', 486.39);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Beer - Upper Canada Light', 221.99);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Wine - White, Antinore Orvieto', 249.07);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Red Cod Fillets - 225g', 477.05);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Ice Cream - Turtles Stick Bar', 984.34);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Cake Circle, Paprus', 527.84);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Jaboulet Cotes Du Rhone', 419.25);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Sole - Dover, Whole, Fresh', 327.25);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Nestea - Iced Tea', 116.63);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Ecolab - Mikroklene 4/4 L', 899.21);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Sauce - Hollandaise', 808.54);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Vacuum Bags 12x16', 759.31);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Bread - Assorted Rolls', 987.15);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Beets - Golden', 97.92);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Garbage Bags - Black', 772.52);
insert into Product (id, product, price) values (NEXTVAL('hibernate_sequence'), 'Flavouring - Rum', 109.29);
